import {
  ArrowLeft,
  ArrowRight,
  Bell,
  BookOpen,
  Bot,
  Calendar,
  CalendarClock,
  Check,
  ChevronDown,
  Circle,
  ClipboardList,
  Clock3,
  Copy,
  ExternalLink,
  Flame,
  FolderKanban,
  GraduationCap,
  Grid2x2,
  House,
  Lamp,
  Library,
  Link,
  LoaderCircle,
  LogOut,
  MessageCircle,
  Newspaper,
  Pencil,
  Plus,
  RefreshCw,
  Search,
  Send,
  Settings,
  Sparkles,
  SquareKanban,
  Trash2,
  Undo2,
  User,
} from 'lucide-react';

const ICONS = {
  'arrow-left': ArrowLeft,
  'arrow-right': ArrowRight,
  bell: Bell,
  book: BookOpen,
  bot: Bot,
  calendar: Calendar,
  'calendar-clock': CalendarClock,
  check: Check,
  'chevron-down': ChevronDown,
  clipboard: ClipboardList,
  clock: Clock3,
  copy: Copy,
  dashboard: Grid2x2,
  'external-link': ExternalLink,
  flame: Flame,
  folder: FolderKanban,
  'graduation-cap': GraduationCap,
  home: House,
  lamp: Lamp,
  library: Library,
  link: Link,
  loader: LoaderCircle,
  logout: LogOut,
  message: MessageCircle,
  news: Newspaper,
  pencil: Pencil,
  plus: Plus,
  refresh: RefreshCw,
  search: Search,
  send: Send,
  settings: Settings,
  sparkles: Sparkles,
  task: SquareKanban,
  trash: Trash2,
  undo: Undo2,
  user: User,
};

export default function AppIcon({ name, size = 18, color = 'currentColor', strokeWidth = 1.8 }) {
  const Icon = ICONS[name] || Circle;
  return <Icon size={size} color={color} strokeWidth={strokeWidth} />;
}
